# Generated by Django 6.0 on 2025-12-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
