# Generated by Django 6.0 on 2025-12-09 16:41

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_airplane_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=airport.models.airplane_image_file_path,
            ),
        ),
    ]
